#!/usr/bin/env bash
# Sets up local clangd support (editor diagnostics/completion) for server/,
# without a local vcpkg install. The real build only ever happens in Docker
# (Dockerfile.server / docker-compose.yml's clion-dev service) — clangd
# running on the host has nowhere to find crow.h, OpenCASCADE, spdlog, etc.
# without help, so this copies those headers out of the clion-dev container
# and points a generated .clangd at them.
#
# Only specific third-party library headers are copied — NOT the container's
# whole /usr/include. That directory is Ubuntu/glibc's own C library headers
# (bits/, features.h, ...), which are incompatible with and must never shadow
# the host compiler's own libc/libc++ (breaks resolution of even <string>).
#
# Re-run this after any dependency version bump in Dockerfile.server.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."   # -> server/
SERVER_DIR="$(pwd)"
REPO_ROOT="$(cd .. && pwd)"

echo "Starting clion-dev container..."
(cd "$REPO_ROOT" && docker compose --profile dev up -d clion-dev)

echo "Extracting headers..."
rm -rf .dev-include
mkdir -p .dev-include/third-party

# Third-party libraries living under /usr/include (apt dev packages) — copied
# individually, never the directory itself.
for item in opencascade asio.hpp asio nlohmann spdlog fmt pugixml.hpp pugiconfig.hpp sqlite3.h openssl; do
    docker cp "git4cad-clion-dev-1:/usr/include/${item}" ".dev-include/third-party/${item}"
done

# Debian/Ubuntu splits some generated headers (e.g. OpenSSL's opensslconf.h)
# into an arch-specific multiarch directory, separate from /usr/include/openssl
# — merge it in.
docker cp git4cad-clion-dev-1:/usr/include/x86_64-linux-gnu/openssl/. \
    .dev-include/third-party/openssl/

# From-source builds (crow, libgit2, libzip, SQLiteCpp) — all of /usr/local/include
# is safe wholesale, it's only ever third-party library headers, never libc.
docker cp git4cad-clion-dev-1:/usr/local/include .dev-include/usr-local-include

echo "Writing .clangd..."
cat > .clangd <<EOF
# Generated by server/scripts/setup-clangd.sh — do not edit by hand.
# Re-run that script after any dependency version bump in Dockerfile.server.
CompileFlags:
  Add:
    - -std=c++23
    # crow.h (v1.2.0) still uses std::result_of, removed from the standard in
    # C++20. GCC's libstdc++ (the real Docker build's stdlib) keeps it around
    # regardless; Apple's libc++ enforces the removal unless told not to —
    # this only affects local clangd analysis, not the real build.
    - -D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES
    - -DASIO_STANDALONE
    - -DFMT_LOCALE
    - -DFMT_SHARED
    - -DJSON_DIAGNOSTICS=0
    - -DJSON_USE_IMPLICIT_CONVERSIONS=1
    - -DSPDLOG_COMPILED_LIB
    - -DSPDLOG_FMT_EXTERNAL
    - -DSPDLOG_SHARED_LIB
    - -DSQLITE_ENABLE_COLUMN_METADATA
    - -I${SERVER_DIR}/src
    - -I${SERVER_DIR}/.dev-include/third-party
    - -I${SERVER_DIR}/.dev-include/third-party/opencascade
    - -I${SERVER_DIR}/.dev-include/usr-local-include
  Compiler: clang++
EOF

echo "Done. Restart clangd in your editor (or just reopen the file) to pick it up."
